# -*- coding: utf-8 -*-
"""assignment12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O82uSRO4PuVDOq40atoELZQx2tD-Xmzf
"""

import numpy as np
import matplotlib.pyplot as plt

#Module for Bayes Theorem
def bayes_theorem(p_e1,p_e2,p_xgiven_e1,p_xgiven_e2):
	p_x= p_e1*p_xgiven_e1 + p_e2*p_xgiven_e2
	numerator1 = p_e1*p_xgiven_e1
	p_e1given_x=numerator1/p_x
	return p_e1given_x

#Probability that man says truth
p_1= 3/4
#Probability that man lie
p_2= 1-p_1
#Probability that die shows 6
p_die_0=1/6
#Probability that die shows number other than 6 
p_die_1= 5/6

#Probability that die shows 6 given the man reports it is six is
prob= bayes_theorem(p_1,p_2,p_die_0, p_die_1)

print(prob)