# -*- coding: utf-8 -*-
"""assignment5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ah5GTj5s5SgY1wjkZoe41E026tEVVhvI
"""

import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB


#Path of ball
x = np.linspace(0,69.28,60)
p=np.poly1d([-0.00833,0.577,0])
for i in range(len(x)):
    y=p(x)
#Plotting parabolic path of ball
plt.plot(x,y,'--',label='Path of cricket ball')

#Initial point of the ball
A=np.array([0,0])

B=np.array([69.28,0])
C=np.array([34.64,0])
D=np.array([34.64,10])
#Generating and Plotting line AB
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:])


#Generating and Plotting line CD
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:])

#Generating and plotting vector v_b
V=np.array([10,4.943])
AV=line_gen(A,V)
plt.plot(AV[0,:],AV[1,:])
plt.annotate(s='', xy=(10,4.943), xytext=(10.3,5.1), arrowprops=dict(arrowstyle='<-'))



#drawing arc
r=5
theta = np.linspace(0.08,0.5,50)
x1 = r*np.cos(theta)
y1 = r*np.sin(theta)
plt.plot(x1,y1)

#Labelling points
plt.plot(0,0,'o',label='Ball Starting Pt.')
plt.text(-0.01,-0.03,'A')
plt.plot(69.28,0,'o',label='Pt. Hitting the same level of the starting pt.')
plt.text(70,0,'B')
plt.plot(34.7,0,'o',label='Distance for the max height')
plt.text(34.64,0,'C')
plt.plot(34.64,10,'o',label='Max. Height')
plt.text(34.64,10.2,'D')
plt.text(6,1,'$ \u03B8 $')
plt.text(2,4,'$v_b$')



plt.xlabel('$Distance$')
plt.ylabel('$Height$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')

#if using termux
plt.savefig('assignment5.png')
#else
#plt.show()