# -*- coding: utf-8 -*-
"""Assignment6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MSqgOH1c_zg2eCfkT3bzT8Uu2wP1nFg-
"""

import numpy as np
import matplotlib.pyplot as plt
 
 
O = np.array(([0,0]))
 
def ellipse_gen(a,b):
    len = 50
    theta = np.linspace(0,2*np.pi,len)
    x_ellipse = np.zeros((2,len))
    x_ellipse[0,:] = a*np.cos(theta)
    x_ellipse[1,:] = b*np.sin(theta)
    x_ellipse = (x_ellipse.T + O).T
    return x_ellipse
 
#Generate line points
def line_gen(A,B):
  len =10
  x_AB = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
 
#Standard Ellipse
a = 4.24264
b = 2.82842
x = ellipse_gen(b,a)
 
#Vertices
A1 = np.array([a,0])
A2 = -A1
B1 = np.array([0,b])
B2 = -B1
# Plotting points
p = np.array([2,3]) 
 
 
#Plotting the ellipse
plt.plot(x[0,:],x[1,:],'b' ,label='ellipse')
 
#Labelling points
plt.plot(0,0, 'o')
plt.text(-0.7 ,-0.3,'O')
plt.plot(2,3, 'o')
plt.text(2.2,3,'p')
 
plt.plot(0,3.162277, 'o')
plt.text(0,3.4,'f1')
plt.plot(0,-3.162277, 'o')
plt.text(0 ,-3.6,'f2')
 
 
plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
 
 
#if using termux
plt.savefig('assignment6.png')
#else
plt.show()